[build-system]
build-backend = "pdm.backend"
requires = [
    "pdm-backend",
]

[project]
name = "jupyter-uv-venv"
version = "0.1.4"
description = "One notebook is one venv, using uv to keep disk space"
readme = "README.md"
authors = [
    { name = "Patrice Ferlet", email = "metal3d@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "ipykernel>=6.30.1",
]

[project.license]
text = "MIT"

[project.optional-dependencies]
dev = [
    "jupyterlab>=4.4.7",
]

[project.urls]
Homepage = "https://gitlab.com/metal3d/jupyter-uv-venv"
Issues = "https://gitlab.com/metal3d/jupyter-uv-kernel/-/issues"
Repository = "https://gitlab.com/metal3d/jupyter-uv-venv"

[project.entry-points.kernelspecs]
jupyter-uv-venv = "jupyter_uv_venv.kernel:get_kernel_spec"

[tool.pdm]
distribution = true
