[project]
name = "mseep-mcp-server-ledger"
version = "0.1.2"
description = "A Model Context Protocol server providing tools to execute Ledger, a powerful command-line accounting system, commands."
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "mcp>=1.4.1",
]
license = "MIT"
keywords = [
    "mcp",
    "ledger",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[dependency-groups]
dev = [
    "mcp[cli]>=1.4.1",
]
