[project]
name = "php-framework-scaffolder"
version = "0.1.119"
description = "A CLI tool to scaffold PHP framework applications"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "gitpython>=3.1.44",
    "jinja2>=3.1.0",
    "packaging>=24.2",
    "pandas>=2.2.3",
    "php-framework-detector>=0.2.15",
    "pygithub>=2.6.1",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "streamlit>=1.44.1",
    "structlog>=25.4.0",
    "typer>=0.15.2",
]

[project.scripts]
php-framework-scaffolder = "php_framework_scaffolder.cli:app"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["php_framework_scaffolder*"]

[tool.setuptools.package-data]
"php_framework_scaffolder" = [
    "templates/**/*",
    "templates/**/.*"
]

[tool.bumpversion]
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[tool.bump-my-version.files]
"pyproject.toml" = [
    'project.version'
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
