[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "mseep-rdkit-mcp-server"
version = "0.1.6"
description = "MCP Server providing RDKit cheminformatics tools."
requires-python = ">=3.8"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Framework :: AsyncIO",
]
dependencies = [
    "mcp==1.11.0",
    "rdkit==2025.3.1",
    "Pillow==11.2.1",
    "openai-agents==0.0.14",
    "pydantic==2.11.5",
    "pydantic-settings==2.9.1",
    "pyyaml",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/tandem-ai-inc/rdkit-mcp-server"
Repository = "https://github.com/tandem-ai-inc/rdkit-mcp-server"

[project.scripts]
rdkit-mcp-server = "rdkit_mcp_server.__main__:main"

[tool.hatch.build.targets.wheel]
packages = [
    "rdkit_mcp",
    "rdkit_mcp_clients",
]
