[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "antelope_interface"
authors =[
    {name = "Brandon Kuczenski", email="bkuczenski@ucsb.edu"}
]
description = "A common interface for accessing LCA data"
readme ={ file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.6"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
         "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering"
]
dependencies = ["synonym_dict >= 0.2.4", "pydantic >= 2.5.0"]
version = "0.3.3.1"

[tool.setuptools.packages.find]
where = ["src"]
