[project]
name = "floofyredpanda"
version = "1.0.5"
description = "A delightfully unhinged socket library with SSL support and caveman energy"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name="shadow113323 "}
]
keywords = ["socket", "ssl", "floof", "panda", "networking", "fun"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",

  "Programming Language :: Python :: 3.12",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Networking",
]

[project.urls]
Homepage = "https://pypi.org/project/floofyredpanda/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
