[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pretty-dir"
description = "A pretty-printed version of dir(obj) for more comfortable debugging"
# Switched to PYPI so that github and pypi can display different info. Github always uses the README.md file and PYPI uses the file set by `project.readme`
readme = "PYPI.md"
requires-python = ">=3.11.0"
dynamic = ["version"]
dependencies = [
  "colorama>=0.4.6",
]
[project.optional-dependencies]
dev = [
  "build>=1.2.2",
  "ruff>=0.12.7",
]
docs = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.6.16",
  "mkdocstrings-python>=0.30.0",
]

[tool.hatch.version]
path = "ppdir/__init__.py"

[tool.hatch.build]
include = [
  "ppdir/**",
]

[tool.coverage.run]
relative_files = true

[tool.doc8]
max-line-length = 120
file-encoding = "utf8"

[tool.ruff]
line-length = 120
preview = true
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN401",  # https://docs.astral.sh/ruff/rules/any-type/
  "CPY001",  # https://docs.astral.sh/ruff/rules/missing-copyright-notice/
  "DOC201",  # https://docs.astral.sh/ruff/rules/docstring-missing-returns/
  "D100",    # https://docs.astral.sh/ruff/rules/undocumented-public-module/
  "D401",    # https://docs.astral.sh/ruff/rules/non-imperative-mood/
  "ERA001",  # https://docs.astral.sh/ruff/rules/commented-out-code/
  "N815",    # https://docs.astral.sh/ruff/rules/mixed-case-variable-in-class-scope/ ignored for now. Can be undone by replacing the pydantic fields with Field(alias=...)
  "PLR1722", # https://docs.astral.sh/ruff/rules/sys-exit-alias/
  "RUF012",
  "SLF001",  # https://docs.astral.sh/ruff/rules/private-member-access/
  "S101",
  "T100",    # https://docs.astral.sh/ruff/rules/debugger/
  "T201",    # https://docs.astral.sh/ruff/rules/print/
  "TD002",
  "TD003",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "D203",    # ignored due to incompatibility with D211
  "D213",    # ignored due to incompatibility with D212
]
