[project]
name = "mseep-mcp-server-calculator"
version = "0.2.7"
description = "A Model Context Protocol server for calculating"
requires-python = ">=3.10"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
keywords = [
    "mcp",
    "llm",
    "math",
    "calculator",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "mcp>=1.4.1",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.license]
text = "MIT"

[project.urls]
Source = "https://github.com/githejie/mcp-server-calculator"

[project.scripts]
mcp-server-calculator = "mcp_server_calculator:main"

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
