[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simpleDicomViewer"
version = "2.0.3"
authors = [
  { name="Justin Kirby", email="justin.kirby@nih.gov" },
]
description = "A package to simplify visualizing DICOM data, including images and segmentations (RTSTRUCT and SEG) via Jupyter/Python."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
  "pydicom",
  "matplotlib",
  "numpy",
  "ipywidgets",
  "rt-utils",
  "ipython"
]

[project.urls]
"Homepage" = "https://github.com/kirbyju/simpleDicomViewer"
"Bug Tracker" = "https://github.com/kirbyju/simpleDicomViewer/issues"
