theme:
  name: material
  features:
    - navigation.sections # Sections are included in the navigation on the left.
    - toc.integrate # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide # header disappears as you scroll
    - content.code.copy
  palette:
    primary: white
  icon:
    repo: fontawesome/brands/github
  logo: _static/favicon.svg
  navigation_depth: 3
  favicon: "_static/favicon.svg"

site_name: pymgcv
site_description: The documentation for the pymgcv software library.
site_author: Daniel Ward
extra:
  generator: false
# site_url: TODO
repo_url: https://github.com/SmoothForge/pymgcv
repo_name: SmoothForge/pymgcv
edit_uri: ""
strict: false # TODO Don't allow warnings during the build process

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

nav:
  - Introduction: index.ipynb # Seems to work
  - Examples:
      - GAMLSS: examples/gamlss.ipynb
      - Smooth-by-categorical: examples/smooth_by_categorical.ipynb
      - Linear functional: examples/linear_functional.ipynb
  - Applied Examples:
      - Ozone: examples/ozone.ipynb
      - Seasonal CO2: examples/seasonal_co2.ipynb
      - Spatial fish eggs: examples/spatial_fish_eggs.ipynb
      - Electricity demand BAM: examples/electricity_bam.ipynb
      - Supplement vs placebo: examples/supplement_vs_placebo.ipynb
  - API Reference:
      - api/gam.md
      - api/terms.md
      - api/basis_functions.md
      - api/families.md
      - api/plot.md
      - api/miscellaneous.md
  - Development:
      - contributing.md

plugins:
  - search:
      # https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - ipynb

  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            docstring_section_style: list
            show_bases: false
            show_source: false
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            line_length: 88
            force_inspection: true
            filters:
              - "!^_"
              - "__init__"
            heading_level: 3
            members_order: source
            show_signature_annotations: true
            extensions:
              - griffe_inherited_docstrings
            merge_init_into_class: true

extra_css:
  - stylesheets/extra.css
