services:
  app:
    build: .
    env_file:
      - app.env
    {% if expose_app_port %}
    ports:
      - "{{ app_port }}:80"
    {% endif %}
    volumes:
      - ./coverage:/var/tmp/coverage/
    restart: always
    depends_on:
    {% if database_type == "mysql" %}
      mysql:
        condition: service_healthy
    {% endif %}
    {% if database_type == "postgres" %}
      postgres:
        condition: service_healthy
    {% endif %}

  {% if database_type == "mysql" %}
  mysql:
    image: mysql:5.7
    env_file:
      - mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
      interval: 10s
      timeout: 20s
      retries: 10
  {% endif %}

  {% if database_type == "postgres" %}
  postgres:
    image: postgres:16
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 10
  {% endif %}

volumes:
  {% if database_type == "mysql" %}
  mysql_data:
  {% endif %}
  {% if database_type == "postgres" %}
  postgres_data:
  {% endif %}
