[project]
name = "mseep-mcp-server-demo"
version = "0.1.6"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-mcp-server-demo = "main:main"

[tool.setuptools]
py-modules = [
    "main",
]
