[project]
name = "mseep-shopify-py-mcp"
version = "0.1.6"
description = "A MCP server project"
requires-python = ">=3.11.6"
dependencies = [
    "mcp>=1.3.0",
    "ShopifyAPI>=1.0.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
shopify-py-mcp = "shopify_py_mcp:main"

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
