[project]
name = "auryn"
version = "1.0.2"
description = "The Auryn Metaprogramming Engine"
authors = [
    {name = "Dan Gittik", email = "dan.gittik@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"
flake8 = "^7.2.0"
isort = "^6.0.1"
mypy = "^1.15.0"
pytest-cov = "^6.1.1"
poethepoet = "^0.33.1"

[tool.poetry.scripts]
auryn = "auryn.cli:cli"

[tool.poe.tasks]
clean = "python dev.py clean"
test = "python dev.py test"
cov = "python dev.py cov"
lint = "python dev.py lint"
type = "python dev.py type"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
