[tool.poetry]
name = "ntfy-notify"
version = "0.1.1"
description = "A Python package for sending notifications via ntfy.sh"
authors = ["Melchior im Dreital <Melchior.im.Dreital@protonmail.com>"]
license = "EUPL-1.2"
readme = "README.md"
packages = [{ include = "ntfy_notify" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications",
    "Topic :: System :: Monitoring",
    "Topic :: Utilities"
]

[project]
name = "ntfy-notify"
version = "0.1.1"
description = "A Python package for sending notifications via ntfy.sh"
authors = [
    {name = "Melchior im Dreital", email = "Melchior.im.Dreital@protonmail.com"}
]
license = {text = "EUPL-1.2"}
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications",
    "Topic :: System :: Monitoring",
    "Topic :: Utilities"
]

[project.urls]
Homepage = "https://gitlab.com/pynpakken/ntfy-notify"
Documentation = "https://gitlab.com/pynpakken/ntfy-notify#readme"
Repository = "https://gitlab.com/pynpakken/ntfy-notify"
Changelog = "https://gitlab.com/pynpakken/ntfy-notify/blob/main/CHANGELOG.md"


# -------------------------------------------------
# Laufzeit‑Abhängigkeiten
# -------------------------------------------------
[tool.poetry.dependencies]
python = ">=3.13, <4.0"
requests = "^2.32"
tomli = "^2.0"
click = "^8.1"
poetry-core = "^2.1.3"

[tool.poetry.group.test.dependencies]
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"

# -------------------------------------------------
# CLI‑Entry‑Point
# -------------------------------------------------

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"

[tool.poetry.scripts]
ntfy-notify = "ntfy-notify.__main__:cli_entrypoint"

# -------------------------------------------------
# Build‑System (wird von Poetry automatisch gesetzt)
# -------------------------------------------------
[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

