[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dolze-image-templates"
version = "0.10.6"
description = "A package for generating Dolze templates"
readme = "README.md"
authors = [
    {name = "Dolze team", email = "dolze@team.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.6"
dependencies = [
    "Pillow>=9.0.0",
    "requests>=2.25.0",
    "typing_extensions>=4.12.2",
    "cairosvg",

    # HTML rendering dependencies (optional)
    "selenium>=4.1.0",
    "webdriver-manager>=3.5.2",
    "playwright"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black",
    "isort",
    "mypy",
]

html = [
    "selenium>=4.1.0",
    "webdriver-manager>=3.5.2",
    "playwright>=1.0.0",
    "imgkit>=1.0.0",
]

all = [
    "Pillow>=9.0.0",
    "requests>=2.25.0",
    "typing_extensions>=4.12.2",
    "cairosvg",

    # HTML rendering dependencies (optional)
    "selenium>=4.1.0",
    "webdriver-manager>=3.5.2",
    "playwright"
]

[tool.setuptools.packages.find]
include = ["dolze_image_templates", "dolze_image_templates.*"]
