[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "mseep-mcp_weather_server"
version = "0.2.3"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
description = "An MCP server for weather information"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.0.0",
    "argparse>=1.4.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.2.1",
    "python-dotenv>=1.0.1",
    "python-dateutil>=2.8.2",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mcp_weather_server = "mcp_weather_server:main"

[project.urls]
Source = "https://github.com/isdaniel/mcp_weather_server"

[tool.hatch.build.targets.wheel]
packages = [
    "src/mcp_weather_server",
]
