[project]
name = "xgae"
version = "0.1.20"
description = "Extreme General Agent Engine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog==6.9.0",
    "langchain-mcp-adapters==0.1.9",
    "langgraph==0.6.5",
    "litellm==1.74.15",
    "mcp==1.13.0",
    "langfuse==2.60.9",
    "langchain==0.3.27",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = ["log/*", ".idea/*"]

[project.scripts]
xgae = "xgae.engine_cli_app:main"
xgae-tools = "xgae.tools.without_general_tools_app:main"
example-fault-tools = "examples.tools.custom_fault_tools_app:main"
example-a2a-tools = "examples.tools.simu_a2a_tools_app:main"
