repos:
  - repo: local
    hooks:
      # STRICT
      - id: pytest-all
        name: И test 路 Run all pytest tests
        entry: pytest
        language: system
        types: [python]
        args: []
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: faq1
        name: И FAQ  路 Have you updated CHANGELOG?
        entry: sleep 5
        language: system
        pass_filenames: false
        always_run: true
      - id: faq2
        name: И FAQ  路 Have you updated version in pyproject.toml?
        entry: sleep 5
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: " security 路 Detect hardcoded secrets"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-format
        name: " python 路 Format with Ruff"
      # STRICT
      - id: ruff
        args: [ '--fix', '--ignore=F401' ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
        name: " filesystem/锔 exec 路 Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: " filesystem/锔 exec 路 Verify script permissions"
      - id: check-case-conflict
        name: " filesystem/ names 路 Check case sensitivity"
      - id: check-illegal-windows-names
        name: " filesystem/ names 路 Validate Windows filenames"
      - id: check-symlinks
        name: " filesystem/ symlink 路 Check symlink validity"
      - id: destroyed-symlinks
        name: " filesystem/ symlink 路 Detect broken symlinks"
