[project]
name = "x_make_markdown_x"
version = "10.0.1"
description = "Makes markdown."
authors = [{name = "Roy GM", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = ['markdown', 'pdfkit']
