[project]
name = "mseep-mcp-adb"
version = "0.1.1"
description = "An MCP server for Android automation using UIAutomator2"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "mcp[cli]>=1.7.0",
    "uiautodev>=0.6.0",
    "uiautomator2>=3.2.9",
    "python-multipart>=0.0.9",
    "ruff>=0.11.8",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-asyncio>=0.26.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-mcp-adb = "server:main"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Please use \\`import python_multipart\\` instead.:PendingDeprecationWarning:starlette\\.formparsers",
]

[tool.setuptools]
py-modules = [
    "server",
]
