[build-system]
requires = ["flit_core >= 3.12.0, <4"]
build-backend = "flit_core.buildapi"

[project]
name = "django-tag-tools"
dynamic = ["version", "description"]
authors = [{name = "kaleissin", email = "kaleissin@gmail.com"}]
readme = "README.rst"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Framework :: Django :: 1.11",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.2",
]
requires-python = ">= 3.9"
dependencies = [
    "django-taggit",
    "fake-factory",
    "factory-boy",
]

[project.urls]
Repository = "https://codeberg.org/Kaleissin/django-tag-tools"

[tool.flit.module]
name = "tagtools"
