[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "expressipy"
version = "2.0.1"
description = "A Python wrapper for the OtakuGIFs API"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
authors = [{ name = "AndehUK" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11", 
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
    "Framework :: AsyncIO",
]
dynamic = ["dependencies"]

[project.urls]
"Issue tracker" = "https://github.com/AndehUK/expressipy/issues"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["expressipy*"]

[tool.setuptools.package-data]
expressipy = ["py.typed"]

[tool.pyright]
include = ["expressipy"]
exclude = ["**/__pycache__"]

reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.8"
typeCheckingMode = "basic"
