[project]
name = "hifiyaml"
version = "0.1.6"
description = "High-fidelity YAML parser that preserves formatting"
readme = "README.md"
authors = [
    { name="Guoqing Ge", email="Guoqing.Ge@noaa.gov" }
]
license = {file = "LICENSE"}
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/hifiyaml/hifiyaml/wiki"
Source = "https://github.com/hifiyaml/hifiyaml"
Tracker = "https://github.com/hifiyaml/hifiyaml/issues"
