[project]
name = "fandom-scraper"
version = "0.6.1"
description = "A simple AI (span-marker) powered fandom scraper"
readme = "README.md"
authors = [
    { name = "AnthonyP57", email = "antonipawlowicz123@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fandom-py==0.2.1",
    "span-marker==1.7.0",
    "transformers==4.47.0",
    "torch==2.5.1",
    "tokenizers==0.21.0",
    "aiohttp==3.11.9",
    "aiohappyeyeballs==2.4.4",
    "aiosignal==1.3.1",
    "beautifulsoup4==4.13.5",
    "regex==2024.11.6",
    "tqdm==4.67.1",
    "numpy==2.1.3",
    "pandas==2.2.3",
    "scikit-learn==1.6.0",
    "scipy==1.14.1",
    "packaging==24.2",
    "pyyaml==6.0.2",
    "attrs==24.2.0",
    "filelock==3.13.1",
    "fsspec==2024.9.0",
    "networkx==3.3",
    "propcache==0.2.1",
    "psutil==6.1.0",
    "pyarrow==18.1.0",
    "requests==2.32.3",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "yarl==1.18.3",

]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[tool.uv.sources]
# Only needed for your local dev environment (won't be published with the package metadata)
torch = [
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[project.scripts]
fandom-scraper = "fandom_scraper:main"
