[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[project]
name = "external-resources"
version = "0.3.0"
description = "Fetch and deploy external resources (CSS, JS, Fonts) for web services"
readme = "README.rst"
requires-python = ">= 3.10"
authors = [
  {name = "Detlef Lannert", email = "detlef@lannert.de"},
]
maintainers = [
  {name = "Detlef Lannert", email = "detlef@lannert.de"},
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["js", "JavaScript", "CSS", "fonts", "vendoring", "web application",
  "resources", "web", "installation"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Software Development :: Build Tools",
  "Typing :: Typed",
]

dependencies = [
  "cyclopts",
  "httpx",
  "msgspec",
  "pyyaml",
  "packaging",
  "pyproject-parser",
  "rich",
  "tomli-w",
  "xdg-base-dirs>=6.0.2",
  "uuid7>=0.1.0",
  "niquests>=3.15.2",
]

[project.scripts]
extres = "external_resources.main:app"

[project.urls]
Homepage = "https://github.com/detlefla/external_resources"
#Documentation = "https://readthedocs.org"
Repository = "https://github.com/detlefla/external_resources.git"
Issues = "https://github.com/detlefla/external_resources/issues"
Changelog = "https://github.com/detlefla/external_resources/blob/master/CHANGELOG.md"


[tool.external-resources]
resource_index = "external_resources.yaml"
requires = [
  "bootstrap",
  "htmx == 1.9.10",
]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = ["migrations"]

[tool.ruff.lint]
ignore = ["F401", "F405"]
task-tags = ["XXX"]

[tool.ruff.lint.per-file-ignores]
# "filename" = [list of codes]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ipython",
    "invoke",
    "mypy",
    "pyproject-parser[cli]",
    "pytest >= 8.4.1",
    "types-invoke",
    "types-PyYAML",
]
