[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yaccounts"
version = "2.4.3"
description = "Package for generating accounting reports from BYU's workday system."
authors = [
    { name = "Jeff Goeders", email = "jgoeders@byu.edu" }
]
dependencies = [
    "requests>=2.32.3",
    "bs4>=0.0.2",
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
    "pyyaml>=6.0.2",
    "pandas>=2.2.3",
    "openpyxl>=3.1.5",
    "appdirs>=1.4.4",
]

[project.scripts]
yaccounts = "yaccounts.cli:main"