[project]
name = "x_make_github_clones_x"
version = "10.0.7"
description = "Makes GitHub repository clones."
authors = [{name = "Roy GM", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = []
