[project]
name = "inchpym"
version = "0.1.18"
description = "LibrerÃ­a de Python para manejo de archivos y DataFrames de Daniel Ochoa"
authors = [
  { name="DanielOchoa", email="df.ochoa202@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.26.0",
    "unidecode>=1.3.6",
    "openpyxl>=3.1.0",
    "pywin32>=306"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
