[project]
name = "pychub-pdm-plugin"
version = "1.0.2"
description = "Pdm build plugin for pychub"
authors = [
    { name = "Steve Storck", email = "steve973@gmail.com" }
]
readme = "README.md"
license = "MIT"
dependencies = [
    "pychub>=1.0.0",
    "pdm>=2.25.0,<3.0.0"
]
packages = [{ include = "pychub_pdm_plugin", from = "src" }]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Archiving :: Packaging",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Software Distribution",
    "Topic :: Utilities"
]
keywords = [
    "bundle",
    "chub",
    "executable",
    "package",
    "packaging",
    "zipapp"
]

[project.entry-points."pdm.build.hook"]
pychub = "pychub_pdm_plugin.plugin:PychubBuildHook"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
