[project]
name = "mseep-playwright-mcp"
version = "0.1.2"
description = "Playwright wrapper for MCP"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.3.0",
    "playwright>=1.50.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
playwright-mcp = "playwright_mcp:main"

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
