[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "v2ray2proxy.VERSION"}

[project]
name = "v2ray2proxy"
# Using dynamic versioning to get from v2ray2proxy
dynamic = ["version"]
authors = [
    {name = "nichind", email = "nichinddev@gmail.com"},
]
description = "ðŸ Convert v2ray (vless://, vmess://, ss:// , trojan://) to local socks5:// & http:// proxies"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "v2ray",
    "v2core",
    "v2ray-core",
    "proxy",
    "vless",
    "vmess",
    "shadowsocks",
    "trojan",
    "python",
    "cli"
]
dependencies = ["psutil"]

[project.urls]
"Homepage" = "https://github.com/nichind/v2ray2proxy"
"Issues" = "https://github.com/nichind/v2ray2proxy/issues"

[tool.setuptools]
packages = {find = {}}

[tool.ruff]
line-length = 140