[project]
name = "mseep-solsecurity-mcp"
version = "0.1.2"
description = "Solana wallet security analysis tool"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
    "python-dotenv",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-solsecurity-mcp = "main:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src",
]

[tool.setuptools]
py-modules = [
    "main",
]
