[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "mseep-mcp-simple-pubmed"
version = "0.1.17"
description = "An MCP server that provides access to PubMed articles through Entrez API."
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastmcp>=2.10.0",
    "biopython",
    "metapub",
    "httpx",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.urls]
Homepage = "https://github.com/andybrandt/mcp-simple-pubmed"

[project.scripts]
mcp-simple-pubmed = "mcp_simple_pubmed.__main__:main"
