[project]
name = "mseep-outlookmcpserver"
version = "0.1.2"
description = "An MCP Server for giving Claude control over Outlook on Mac"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "azure-identity",
    "msgraph-core",
    "msgraph-sdk",
    "pytest",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-outlookmcpserver = "main:main"

[tool.setuptools]
py-modules = [
    "main",
]
