[project]
name = "x_make_persistent_env_var_x"
version = "10.0.3"
description = "Generic persistent environment variable setter for Windows (User scope)."
authors = [{name = "Roy GM", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = []
