name: Pylembic testing ğŸ§ª and coverage report generation ğŸ“

on:
  - push

jobs:
  testing:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    name: Python Testing and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Tests
        uses: maekind/github-actions/.github/actions/python-testing-and-coverage@main
        with:
          python_version: ${{ matrix.python-version }}
          coverage_path: "./src"

  upload-coverage:
    name: Upload Coverage to Codecov
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Upload Code Coverage
        uses: maekind/github-actions/.github/actions/upload-codecov-coverage@main
        with:
          codecov_token: ${{ secrets.CODECOV_GH_PYLEMBIC }}
