[package]
name = "rustlens"
version = "0.5.2"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlens"
crate-type = ["lib", "cdylib"]

[dependencies]
ellip = "0.3.3"
interp = "2.1.1"
numdiff = "0.2.0"
pyo3 = "0.26.0"
quadrature = "0.1.2"
rayon = "1.11.0"
