[project]
name = "mseep-eagle-mcp-server"
version = "0.1.2"
description = "An MCP server for Eagle"
requires-python = ">=3.13"
dependencies = [
    "fastapi-mcp>=0.3.3",
    "httpx>=0.28.1",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-eagle-mcp-server = "main:main"

[tool.setuptools]
py-modules = [
    "main",
]
