[project]
name = "sinapsis-chatbots"
version = "0.5.3"
description = "Mono repo with packages for text completion tasks"
authors = [
    {name = "SinapsisAI", email = "dev@sinapsis.tech"},
]
readme = "README.md"
license-files = ["LICENSE"]
dependencies = [
    "sinapsis>=0.1.1",
]


[dependency-groups]
dev = [
    "ruff>=0.8.3",
    "pre-commit>=4.0.1",
]
[project.optional-dependencies]
gradio-app = [
    "sinapsis[webapp]>=0.2.2",
]



all = [
    "sinapsis-chatbots[gradio-app]",
    "sinapsis-chat-history[all]",
    "sinapsis-llama-cpp[all]",
    "sinapsis-chatbots-base[all]",
    "sinapsis-llama-index[all]",
    "sinapsis-anthropic[all]",
    "sinapsis-mem0[all]",
]
chatbot-app = [
    "sinapsis[webapp]>=0.2.15",
]
chatbot = [
    "sinapsis-langchain-readers[langchain-pdfs-readers,langchain-wikipedia-readers]>=0.1.5",
]

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/*.egg-info"]

[tool.setuptools]
packages = { find = { where = ["packages"] } }


[[tool.uv.index]]
url = "https://pypi.sinapsis.tech/"

[tool.uv.sources]
sinapsis-chatbots-base = { workspace = true }
sinapsis-chat-history = {workspace = true}
sinapsis-llama-cpp = { workspace = true }
sinapsis-llama-index = { workspace = true }
sinapsis-anthropic = { workspace = true }
sinapsis-mem0 = { workspace = true }

[tool.ruff]
lint.select = [
    "ARG",
    "BLE",
    "C4",
    "E",
    "F",
    "FIX",
    "FLY",
    "I",
    "PERF",
    "PIE",
    "RUF",
    "RSE",
    "SIM",
    "SLOT",
    "T10",
    "T20",
    "TD",
    "TID",
]
line-length = 120



[project.urls]
Homepage = "https://sinapsis.tech"
Documentation = "https://docs.sinapsis.tech/docs"
Tutorials = "https://docs.sinapsis.tech/tutorials"
Repository = "https://github.com/Sinapsis-AI/sinapsis-chatbots.git"
