[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "mseep-mcpgex"
version = "0.1.6"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
description = "MCP server for testing and validating regex patterns against test cases"
keywords = [
    "mcp",
    "regex mcp",
    "regex finder",
    "regex llm",
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "mcp>=0.1.0",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mcpgex = "mcpgex:main"

[project.urls]
Homepage = "https://github.com/PatzEdi"
Repository = "https://github.com/PatzEdi/MCPGex"
"Bug Tracker" = "https://github.com/PatzEdi/MCPGex/issues"

[tool.hatch.build.targets.wheel]
packages = [
    "src/mcpgex",
]
