[project]
name = "mseep-food-delivery-mcp"
version = "0.1.3"
description = ""
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
requires-python = ">=3.10,<4.0"
dependencies = [
    "firebase-admin>=6.9.0",
    "google-cloud-firestore>=2.21.0",
    "mcp[cli]>=1.11.0",
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-food-delivery-mcp = "server:main"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
]

[tool.setuptools]
py-modules = [
    "server",
]
