[project]
name = "x_make_mermaid_x"
version = "11.0.0"
description = "Mermaid diagram builder."
authors = [{name = "RRGM of the Primus Pilus Night Watch AI Corporation", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = []
