[project]
name = "abs-nosql-integration-core"
version = "0.3.3"
description = "Core utilities for building OAuth-based integrations in FastAPI applications with use of NoSql db"
authors = [
    {name = "AutoBridgeSystems", email = "info@autobridgesystems.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "fastapi >=0.95.0,<2.0.0",
    "pydantic >=2.0.0,<3.0.0",
    "abs-exception-core (>=0.2.0,<0.3.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "abs-nosql-repository-core (>=0.11.5,<0.12.0)",
    "abs-integration-core (>=0.2.3,<0.3.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
