[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FinToolsAP"
version = "1.14.16"
authors = [
  { name="Andrew Maurice Perry", email="andrewpe@berkeley.edu" },
]
description = "This package is a comprehensive Python package designed for researchers and data analysts in economics and finance. It provides streamlined tools for managing, processing, and querying large datasets using a local SQLite database, as well as convenient data manipulation utilities compatible with both pandas and polars."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "pandas>=1.5,<3.0",
  "pathlib>=1.0,<2.0",
  "sqlalchemy>=1.4,<2.5",
  "matplotlib>=3.5,<4.0",
  "tqdm>=4.64,<5.0",
  "twine>=4.0,<7.0",
  "build>=0.10,<1.0",
  "pyarrow>=10.0,<25.0",
  "statsmodels>=0.14,<1.0",
  "pdoc>=9.0,<16.0",
  "wrds>=3.2,<4.0",
  "connectorx>=0.4,<1.0",
  "polars>=0.16,<2.0",
  "bottleneck==1.3.6",
  "seaborn>=0.12,<1.0",
  "knockknock>=0.1.0,<0.5.0",
  "linearmodels>=4.36,<7.0",
]

[project.urls]
"Homepage" = "https://github.com/AndrewPerry-Haas/FinToolsAP"
"Bug Tracker" = "https://github.com/AndrewPerry-Haas/FinToolsAP/issues"
