[project]
name = "cprdspy"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.0.4",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "nbformat==5.10.4",
    "numpy>=2.2.5",
    "plotly>=6.0.1",
]
