[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "railtracks"
authors = [
    { name = "Logan Underwood", email = "logan@railtown.ai" },
    { name = "Levi Varsanyi", email = "levi@railtown.ai" },
    { name = "Jaime Bueza", email = "jaime@railtown.ai" },
    { name = "Amir Refaee", email = "amir@railtown.ai" },
    { name = "Aryan Ballani", email = "aryan@railtown.ai" },
    { name = "Tristan Brown", email = "tristan@railtown.ai" }
]
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version", "description"]
dependencies = [
  "colorama >= 0.4.6",
  "litellm[proxy] >= 1.70.2",
  "mcp >= 1.9.0",
  "openai < 1.100.0",
  "pydantic >= 2.5.3, <3",
  "python-dotenv >= 1.0.0",
  "PyYAML >= 6.0"
]

[project.optional-dependencies]
chat = [
    "fastapi >= 0.104.0"
]
# For each Integration package depenedcies go here.
rag = [
    "litellm[proxy] >= 1.70.2",
    "openai < 1.100.0"
]
# the integrations submodule will be list a of the above deps
integrations = [
    # currently empty
]
all = [
    "railtracks[chat,rag,integrations]"
]

core = [
    "railtracks[chat]"
]

[project.urls]
documentation = "https://railtown.github.io/railtracks"
railtracks = "https://railtracks.org"
repository = "https://github.com/RailtownAI/railtracks"
ui-repository = "https://github.com/RailtownAI/railtracks-visualizer"
railtown = "https://railtown.ai"

[tool.flit.module]
name = "railtracks"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.setuptools.package-data]
railtracks = ["py.typed"]