[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "aviyal_desktop"
version = "0.0.2"
description = "an unofficial tool for running anvil app locally in desktop environment"
authors = [
	{ name = "keralaboy", email = "keralaboypypi@keralaboy.anonaddy.com" }
    ]
readme = "README.md"
license =  "AGPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = [   "desktop", "anvi" , "run", "local" ,"generate"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

requires-python = ">=3.6"
dependencies = ["anvil-app-server","pyargman"]

[project.urls]
Homepage = "https://github.com/its-me-abi/aviyal_desktop_library"

[tool.setuptools]
packages = ["aviyal_desktop"]
include-package-data = true

