[project]
name = "fandom-scraper"
version = "0.6.3"
description = "A simple AI (span-marker) powered fandom scraper"
readme = "README.md"
authors = [
    { name = "AnthonyP57", email = "antonipawlowicz123@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "accelerate==1.10.1",
    "aiohappyeyeballs==2.4.4",
    "aiohttp==3.11.9",
    "aiosignal==1.3.1",
    "attrs==24.2.0",
    "beautifulsoup4==4.13.5",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.3",
    "datasets==3.1.0",
    "dill==0.3.8",
    "evaluate==0.4.5",
    "fandom-py==0.2.1",
    "filelock==3.13.1",
    "frozenlist==1.5.0",
    "fsspec==2024.9.0",
    "huggingface-hub==0.26.3",
    "idna==3.10",
    "jinja2==3.1.6",
    "joblib==1.5.2",
    "markupsafe==3.0.2",
    "mpmath==1.3.0",
    "multidict==6.6.4",
    "multiprocess==0.70.16",
    "networkx==3.3",
    "numpy==2.1.3",
    "nvidia-cublas-cu11==11.11.3.6 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cuda-cupti-cu11==11.8.87 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cuda-nvrtc-cu11==11.8.89 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cuda-runtime-cu11==11.8.89 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cudnn-cu11==9.1.0.70 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cufft-cu11==10.9.0.58 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-curand-cu11==10.3.0.86 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cusolver-cu11==11.4.1.48 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-cusparse-cu11==11.7.5.86 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-nccl-cu11==2.21.5 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-nvjitlink-cu12==12.4.127 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "nvidia-nvtx-cu11==11.8.86 ; sys_platform == 'linux' or sys_platform == 'win32'",
    "packaging==24.2",
    "pandas==2.2.3",
    "propcache==0.2.1",
    "psutil==6.1.0",
    "pyarrow==18.1.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "regex==2024.11.6",
    "requests==2.32.3",
    "safetensors==0.6.2",
    "scikit-learn==1.6.0",
    "scipy==1.14.1",
    "seqeval==1.2.2",
    "six==1.17.0",
    "soupsieve==2.8",
    "span-marker==1.7.0",
    "sympy==1.13.1",
    "threadpoolctl==3.6.0",
    "tokenizers==0.21.0",
    "torch==2.5.1",
    "tqdm==4.67.1",
    "transformers==4.47.0",
    "triton==3.1.0",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "xxhash==3.5.0",
    "yarl==1.18.3",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[project.scripts]
fandom-scraper = "fandom_scraper:main"
