[project]
name = "x_make_pypi_x"
version = "10.0.4"
description = "Makes PyPI packages."
authors = [{name = "Roy GM", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = ['markdown', 'pdfkit']
