[tool.poetry]
name = "bella-lumiere"
version = "0.0.0"
description = "Live Utilities for Model Inspection and Exploration of Relevant Effects"
authors = ["gabriele-marino <gabmarino.8601@gmail.com>"]
readme = "README.md"
packages = [
    { include = "lumiere" }  # explicitly tell Poetry your code is in lumiere/
]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"

dash = "^3.2.0"
dash-bootstrap-components = "^2.0.4"
polars = "^1.32.3"
scipy = "^1.16.1"
shap = "^0.48.0"
p-tqdm = "^1.4.2"

[tool.poetry.group.dev.dependencies]
plotly-stubs = "^0.0.6"
scipy-stubs = "^1.16.1.1"

[tool.poetry.scripts]
lumiere-run = "lumiere.main:main"

[tool.pyright]
typeCheckingMode = "strict"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
