[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "orchagent-cli"
version = "0.1.4"
description = "CLI for the Orchagent API"
authors = [{ name = "Orchagent", email = "dev@example.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "typer[all]>=0.12",
  "rich>=13.0",
  "orchagent>=0.1.3"
]

[project.scripts]
orch = "orchcli.main:app"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/eladrave/orchagent-cli"
