[project]
name = "mseep-cmr-search-mcp"
version = "0.1.2"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "earthaccess>=0.14.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"
