# event/pyproject.toml

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openstarlab-spaceEval"
version = "0.0.5"
description = "openstarlab space eval package"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name="Calvin Yeung", email="yeung.chikwong@g.sp.m.is.nagoya-u.ac.jp" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "tqdm",
    "opencv-python",
    "joblib",
]

license = { text = "Apache License 2.0" }

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"spaceeval.sports.soccer.obso.c_obso_repo" = ["*.csv"]

[project.urls]
Homepage = "https://github.com/open-starlab/"
