[project]
name = "x_make_markdown_x"
version = "11.0.0"
description = "Makes markdown."
authors = [{name = "RRGM of the Primus Pilus Night Watch AI Corporation", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = ['markdown', 'pdfkit']
