[package]
name = "polars_bio"
version = "0.15.1"
edition = "2021"
readme = "README.md"

[lib]
name = "polars_bio"
crate-type= ["cdylib"]




[dependencies]
datafusion-python = "48.0.0"
pyo3 = { version = "0.24.2", features = ["extension-module", "abi3"] }
pyo3-log = "0.12.4"
sequila-core = { git = "https://github.com/biodatageeks/sequila-native.git", rev = "745d40f77da7ced5d540f9285eb5123ba12682ff" }

datafusion = { version = "48.0.1"}
arrow = "55.0.0"
arrow-schema = "55.0.0"
arrow-array = { version = "55.0.0", features = ["ffi"] }
tokio = {version = "1.42.0", features = ["full", "tracing"]}
log = "0.4.22"
tracing = { version = "0.1.41", features = ["log"] }
futures-util = "0.3.31"



polars = { git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee", features = ["dtype-full"]}
polars-plan = { git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee", features = ["parquet", "cloud", "serde"] }
polars-lazy = { git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee",  features = ["parquet", "new_streaming", "streaming", "csv", "cse", "dtype-full"]}
polars-core = {git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee"}
polars-arrow =  { git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee"}
polars-python = { git = "https://github.com/mwiewior/polars.git" , rev = "da42ae21ca9c25bc14562e36e07cf02eafd620ee"}


datafusion-bio-format-vcf = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-core = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-gff = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-fastq = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-bam = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-bed = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }
datafusion-bio-format-fasta = { git = "https://github.com/biodatageeks/datafusion-bio-formats.git", rev = "f62b38bf2b72c3b731fae4abf4a2c68559a157b4" }



async-trait = "0.1.86"
futures = "0.3.31"
coitrees = "0.4.0"
fnv = "1.0.7"
rand = "0.8.5"
