[project]
name = "secrecy"
version = "0.1.0dev7"
description = "A symmetric encryption utility."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.0",
    "cryptography>=44.0.3",
    "platformdirs>=4.4.0",
    "python-dotenv>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
secrecy = "secrecy:cli"

