[project]
name = "mseep-mcpcrashcourse"
version = "0.1.5"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.7",
    "mcp[cli]>=1.6.0",
    "nest-asyncio>=1.6.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-mcpcrashcourse = "main:main"

[tool.setuptools]
py-modules = [
    "main",
]
