[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nodejobs"
version = "0.3.0"
description = "A simple jobâ€management library with Processes, JobDB, and Jobs classes"
readme = "README.md"
requires-python = ">=3.0"
license = { text = "MIT" }
authors = [
  { name = "Justin Girard", email = "justingirard@decelium.com" }
]

classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Topic :: System :: Monitoring",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
urls = { "Homepage" = "https://github.com/Decelium/nodejobs" }

dependencies = [
  "psutil"
]

[project.scripts]
# To expose a console script, uncomment and adjust:
# nodejobs-run = "nodejobs.jobs:main"

[tool.setuptools]
packages = { find = { exclude = ["tests*", "docs*"] } }

