[project]
name = "x_make_github_clones_x"
version = "11.0.0"
description = "Makes GitHub repository clones."
authors = [{name = "RRGM of the Primus Pilus Night Watch AI Corporation", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = []
