[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "giget"
version = "0.4.17"
description = "A simple tool to download files/folders from GitHub repositories"
authors = [
  { name = "Ronit Naik", email = "ronitnaik122@gmail.com" }
]
readme = "README.md"
license = { text = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "requests"
]
keywords = ["github", "download", "cli", "git"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.scripts]
giget = "giget.cli:main"

[project.urls]
Homepage = "https://github.com/RonitNaik122/GitLoad"
Repository = "https://github.com/RonitNaik122/GitLoad"
Issues = "https://github.com/RonitNaik122/GitLoad/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["giget*"]

[tool.setuptools]
license-files = []