[project]
name = "mseep-storyblok-mcp-server"
version = "1.0.3"
description = "MCP server for storyblok"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
mseep-storyblok-mcp-server = "server:main"

[tool.setuptools]
py-modules = [
    "server",
]
