[project]
name = "mseep-bocha-search-mcp"
version = "0.0.3"
description = "A"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.readme]
content-type = "text/plain"
text = "Package managed by MseeP.ai"

[project.scripts]
bocha-search-mcp = "bocha_search_mcp:main"

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
