[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shell-lib"
version = "0.20"
authors = [
  {name="Ma Lin", email="malincns@163.com"},
  {name="Google Gemini", email="no@no.com"}
]
description = "A simple Python utility to simplify shell-like operations."
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Topic :: System :: Shells",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://bitbucket.org/wjssz/shell_lib"

[tool.setuptools.packages.find]
where = ["."]