[package]
name = "rustmodels"
version = "0.1.13"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustmodels"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.1"

# polars = { version = "0.50.0", features = ["lazy"], default-features = false }
# pyo3-polars = "0.23.0"

# ndarray = "0.16.1"
# ndarray-linalg = "0.17.0"

indexmap = "2.10.0"

arrow = "56.0.0"
pyo3-arrow = "0.11.0"
# faer = "0.22.6"
# ndarray = "0.16.1"
