[project]
name = "csj-openapi-mcp"
version = "0.1.7"
description = "Excel MCP Server for manipulating Excel files"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.25.0",
    "fastmcp",
]

[tool.uv.workspace]
members = ["venv"]

[project.scripts]
csj-openapi-mcp = "csjopenapimcp.server:main"
