[project]
name = "amazon_pricepal"
version = "0.1.2"
description = "A package to fetch Amazon product prices."
authors = [
    { name = "David", email = "daviddum345@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "beautifulsoup4"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"