[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
# requires = ["uv_build >= 0.7.19, <0.9.0"]
# build-backend = "uv_build"

[project]
name = "hydrocivil"
version = "1.1.4"
readme = "README.md"
requires-python = ">=3.12"
authors = [
  { name="Lucas Glasner", email="lgvivanco96@gmail.com" },
]
description = "a package for hydrological methods in enviromental engineering"
dependencies = [
    "dask",
    "gdal",
    "geopandas",
    "ipykernel",
    "matplotlib",
    "netCDF4",
    "networkx",
    "numba",
    "numpy",
    "openpyxl",
    "pandas",
    "rasterio",
    "shapely",
    "xarray",
    "rioxarray",
    "whitebox_workflows"
]


[project.urls]
Homepage = "https://github.com/lucasglasner/hydrocivil"
Issues = "https://github.com/lucasglasner/hydrocivil/issues"