[project]
name = "x_make_yahw_x"
version = "10.0.4"
description = "Really simple 'Yet Another Hello World' package."
authors = [{name = "Roy GM", email = "eye4357@outlook.com"}]
license = "MIT"
dependencies = []
